db:
  image: postgres:9.4.4
  ports:
    - "5432"
  env_file:
    - '.env.db'
  volumes:
    - ./docker/volumes/postgres:/var/lib/postgresql/data

web:
  build: .
  volumes:
    - .:/tdman
  ports:
    - "3002:3000"
  links:
    - db
  env_file:
    - '.env.web'
  command: bash -c "rm -rf tmp/* && foreman start"
